### ISSUE TITLE
Inquiry Regarding Interaction Terms in DLNM Models

### ISSUE THREAD

**Issue by deulofeu1** [gasparrini/CTS-smallarea#1]
I am currently researching the application of Distributed Lag Non-Linear Models (DLNM) in relation to temperature and health outcomes.
I recently read your insightful article, A Tutorial on the Case Time Series Design for Small-Area Analysis, and I found the accompanying R code particularly helpful. I noticed in your code that you define interaction cross-bases with the linear IMD score as follows:
```
# DEFINE INTERACTION CROSS-BASES WITH LINEAR IMD SCORE
intval <- quantile(lndmsoaimd$imdscore, c(0.25, 0.75))
cbint1 <- cbtmean * (datafull$imdscore - intval[1])
cbint2 <- cbtmean * (datafull$imdscore - intval[2])
```
This approach to specifying the interaction between the temperature cross-basis and the linear poverty index has intrigued me. I am eager to understand why multiplying the temperature cross-basis by the poverty index matrix effectively represents their interaction.
Additionally, I am currently working on a DLNM model that focuses on temperature-related health visits at a specific location. I also have a time-varying socioeconomic indicator in my dataset. Would it be possible to incorporate the interaction between this socioeconomic indicator and temperature in a similar manner?
I would greatly appreciate any insights you could provide regarding these questions. Thank you for your time and consideration.

**Comment by gasparrini** [comment]
Thanks for your interest, but I advise keeping this section for discussing issues with the code, and not general inquiries about the methodology.
I can see that you sent me a similar question by email, and I will reply to that one.
Best
-AG
